
main: MCTruth_ntuple_create.cc
	g++ -I /usr/common/usg/software/ROOT/6.04.00/include/ `root-config --cflags --libs` -o MCTruth_ntuple_create MCTruth_ntuple_create.cc /cvmfs/lz.opensciencegrid.org/BACCARAT/release-4.3.7/x86_64-slc6-gcc48-opt/lib/libBaccMCTruthEvent.so
